"""
Reply Data Access Object.

Provides async database operations for replies table using asyncpg.
Handles moderator and LLM-generated replies to tasks.
"""

from datetime import datetime
from typing import Optional, List, Dict, Any
import asyncpg
import json


class ReplyDAO:
    """
    Data Access Object for replies table.

    Manages replies generated by moderators or LLMs in response to tasks.
    """

    @staticmethod
    async def create_reply(
        conn: asyncpg.Connection,
        task_id: int,
        content: str,
        generated_by: str = 'human',
        llm_confidence: Optional[float] = None,
        edit_of: Optional[int] = None,
    ) -> int:
        """
        Create a new reply for a task.

        Args:
            conn: AsyncPG database connection
            task_id: ID of the task this reply addresses
            content: Reply text content
            generated_by: Reply source ('human' | 'llm') (default: 'human')
            llm_confidence: LLM confidence score 0.0-1.0 (optional, for LLM replies)
            edit_of: ID of original reply if this is an edit (optional)

        Returns:
            int: ID of the created reply

        Raises:
            asyncpg.ForeignKeyViolationError: If task_id or edit_of invalid
            asyncpg.PostgresError: On other database errors

        Example:
            >>> reply_id = await ReplyDAO.create_reply(
            ...     conn=conn,
            ...     task_id=42,
            ...     content='Thank you for your message!',
            ...     generated_by='human'
            ... )
        """
        query = """
            INSERT INTO replies (
                task_id, content, generated_by, llm_confidence,
                confirmed, edit_of, created_at
            )
            VALUES ($1, $2, $3, $4, $5, $6, $7)
            RETURNING id
        """

        row = await conn.fetchrow(
            query,
            task_id,
            content,
            generated_by,
            llm_confidence,
            False,  # Not confirmed by default
            edit_of,
            datetime.utcnow(),
        )

        return row['id']

    @staticmethod
    async def get_reply_by_id(
        conn: asyncpg.Connection,
        reply_id: int,
    ) -> Optional[Dict[str, Any]]:
        """
        Retrieve a reply by its ID.

        Args:
            conn: AsyncPG database connection
            reply_id: Reply ID

        Returns:
            Dictionary with reply data or None if not found

        Example:
            >>> reply = await ReplyDAO.get_reply_by_id(conn, 123)
            >>> if reply:
            ...     print(f"Content: {reply['content']}")
            ...     print(f"Confirmed: {reply['confirmed']}")
        """
        query = """
            SELECT
                id, task_id, content, generated_by, llm_confidence,
                confirmed, posted_at, platform_ref, edit_of, created_at
            FROM replies
            WHERE id = $1
        """

        row = await conn.fetchrow(query, reply_id)
        return dict(row) if row else None

    @staticmethod
    async def get_replies_for_task(
        conn: asyncpg.Connection,
        task_id: int,
        include_edits: bool = True,
    ) -> List[Dict[str, Any]]:
        """
        Retrieve all replies for a specific task.

        Args:
            conn: AsyncPG database connection
            task_id: Task ID
            include_edits: Include edited versions of replies (default: True)

        Returns:
            List of reply dictionaries ordered by created_at ASC

        Example:
            >>> replies = await ReplyDAO.get_replies_for_task(conn, task_id=42)
            >>> for reply in replies:
            ...     print(f"{reply['generated_by']}: {reply['content']}")
        """
        if include_edits:
            query = """
                SELECT
                    id, task_id, content, generated_by, llm_confidence,
                    confirmed, posted_at, platform_ref, edit_of, created_at
                FROM replies
                WHERE task_id = $1
                ORDER BY created_at ASC
            """
        else:
            query = """
                SELECT
                    id, task_id, content, generated_by, llm_confidence,
                    confirmed, posted_at, platform_ref, edit_of, created_at
                FROM replies
                WHERE task_id = $1 AND edit_of IS NULL
                ORDER BY created_at ASC
            """

        rows = await conn.fetch(query, task_id)
        return [dict(row) for row in rows]

    @staticmethod
    async def get_latest_reply_for_task(
        conn: asyncpg.Connection,
        task_id: int,
    ) -> Optional[Dict[str, Any]]:
        """
        Get the most recent reply for a task.

        Args:
            conn: AsyncPG database connection
            task_id: Task ID

        Returns:
            Dictionary with reply data or None if no replies exist

        Example:
            >>> latest = await ReplyDAO.get_latest_reply_for_task(conn, task_id=42)
        """
        query = """
            SELECT
                id, task_id, content, generated_by, llm_confidence,
                confirmed, posted_at, platform_ref, edit_of, created_at
            FROM replies
            WHERE task_id = $1
            ORDER BY created_at DESC
            LIMIT 1
        """

        row = await conn.fetchrow(query, task_id)
        return dict(row) if row else None

    @staticmethod
    async def mark_reply_confirmed(
        conn: asyncpg.Connection,
        reply_id: int,
    ) -> bool:
        """
        Mark a reply as confirmed by moderator.

        Used when a moderator approves an LLM-generated reply or confirms
        their own reply before sending.

        Args:
            conn: AsyncPG database connection
            reply_id: Reply ID

        Returns:
            True if reply was updated, False if reply not found

        Example:
            >>> confirmed = await ReplyDAO.mark_reply_confirmed(conn, reply_id=123)
        """
        query = """
            UPDATE replies
            SET confirmed = TRUE
            WHERE id = $1
        """

        result = await conn.execute(query, reply_id)
        return result.split()[-1] != '0'

    @staticmethod
    async def mark_reply_posted(
        conn: asyncpg.Connection,
        reply_id: int,
        platform_ref: str,
    ) -> bool:
        """
        Mark a reply as successfully posted to a platform.

        Args:
            conn: AsyncPG database connection
            reply_id: Reply ID
            platform_ref: JSON string with posting info
                         e.g., '{"platform": "discord", "message_id": "123"}'

        Returns:
            True if reply was updated, False if reply not found

        Example:
            >>> import json
            >>> ref = json.dumps({"platform": "discord", "message_id": "999"})
            >>> posted = await ReplyDAO.mark_reply_posted(conn, reply_id=123, platform_ref=ref)
        """
        query = """
            UPDATE replies
            SET posted_at = $1,
                platform_ref = $2
            WHERE id = $3
        """

        result = await conn.execute(
            query,
            datetime.utcnow(),
            platform_ref,
            reply_id,
        )

        return result.split()[-1] != '0'

    @staticmethod
    async def update_reply_content(
        conn: asyncpg.Connection,
        reply_id: int,
        new_content: str,
    ) -> bool:
        """
        Update the content of a reply.

        Note: For major changes, consider creating a new reply with edit_of
        pointing to the original instead.

        Args:
            conn: AsyncPG database connection
            reply_id: Reply ID
            new_content: New reply content

        Returns:
            True if reply was updated, False if reply not found

        Example:
            >>> updated = await ReplyDAO.update_reply_content(
            ...     conn, reply_id=123, new_content='Updated message'
            ... )
        """
        query = """
            UPDATE replies
            SET content = $1
            WHERE id = $2
        """

        result = await conn.execute(query, new_content, reply_id)
        return result.split()[-1] != '0'

    @staticmethod
    async def get_confirmed_replies(
        conn: asyncpg.Connection,
        task_id: Optional[int] = None,
        limit: int = 100,
    ) -> List[Dict[str, Any]]:
        """
        Retrieve confirmed replies, optionally filtered by task.

        Args:
            conn: AsyncPG database connection
            task_id: Filter by task ID (None for all tasks)
            limit: Maximum number of replies to return (default: 100)

        Returns:
            List of reply dictionaries ordered by created_at DESC

        Example:
            >>> confirmed = await ReplyDAO.get_confirmed_replies(conn, limit=50)
        """
        if task_id is not None:
            query = """
                SELECT
                    id, task_id, content, generated_by, llm_confidence,
                    confirmed, posted_at, platform_ref, edit_of, created_at
                FROM replies
                WHERE confirmed = TRUE AND task_id = $1
                ORDER BY created_at DESC
                LIMIT $2
            """
            rows = await conn.fetch(query, task_id, limit)
        else:
            query = """
                SELECT
                    id, task_id, content, generated_by, llm_confidence,
                    confirmed, posted_at, platform_ref, edit_of, created_at
                FROM replies
                WHERE confirmed = TRUE
                ORDER BY created_at DESC
                LIMIT $1
            """
            rows = await conn.fetch(query, limit)

        return [dict(row) for row in rows]

    @staticmethod
    async def get_posted_replies(
        conn: asyncpg.Connection,
        task_id: Optional[int] = None,
        limit: int = 100,
    ) -> List[Dict[str, Any]]:
        """
        Retrieve replies that have been posted to platforms.

        Args:
            conn: AsyncPG database connection
            task_id: Filter by task ID (None for all tasks)
            limit: Maximum number of replies to return (default: 100)

        Returns:
            List of reply dictionaries ordered by posted_at DESC

        Example:
            >>> posted = await ReplyDAO.get_posted_replies(conn, task_id=42)
        """
        if task_id is not None:
            query = """
                SELECT
                    id, task_id, content, generated_by, llm_confidence,
                    confirmed, posted_at, platform_ref, edit_of, created_at
                FROM replies
                WHERE posted_at IS NOT NULL AND task_id = $1
                ORDER BY posted_at DESC
                LIMIT $2
            """
            rows = await conn.fetch(query, task_id, limit)
        else:
            query = """
                SELECT
                    id, task_id, content, generated_by, llm_confidence,
                    confirmed, posted_at, platform_ref, edit_of, created_at
                FROM replies
                WHERE posted_at IS NOT NULL
                ORDER BY posted_at DESC
                LIMIT $1
            """
            rows = await conn.fetch(query, limit)

        return [dict(row) for row in rows]

    @staticmethod
    async def delete_reply(
        conn: asyncpg.Connection,
        reply_id: int,
    ) -> bool:
        """
        Delete a reply by ID.

        Args:
            conn: AsyncPG database connection
            reply_id: Reply ID

        Returns:
            True if reply was deleted, False if reply not found

        Example:
            >>> deleted = await ReplyDAO.delete_reply(conn, reply_id=123)
        """
        query = "DELETE FROM replies WHERE id = $1"
        result = await conn.execute(query, reply_id)
        return result.split()[-1] != '0'

    @staticmethod
    async def get_reply_history(
        conn: asyncpg.Connection,
        reply_id: int,
    ) -> List[Dict[str, Any]]:
        """
        Get edit history for a reply (all versions including the original).

        Args:
            conn: AsyncPG database connection
            reply_id: Original reply ID

        Returns:
            List of reply dictionaries showing edit history, ordered chronologically

        Example:
            >>> history = await ReplyDAO.get_reply_history(conn, reply_id=100)
            >>> for version in history:
            ...     print(f"Version {version['id']}: {version['content']}")
        """
        query = """
            WITH RECURSIVE reply_versions AS (
                -- Base case: the original reply
                SELECT
                    id, task_id, content, generated_by, llm_confidence,
                    confirmed, posted_at, platform_ref, edit_of, created_at
                FROM replies
                WHERE id = $1

                UNION ALL

                -- Recursive case: find all edits
                SELECT
                    r.id, r.task_id, r.content, r.generated_by, r.llm_confidence,
                    r.confirmed, r.posted_at, r.platform_ref, r.edit_of, r.created_at
                FROM replies r
                INNER JOIN reply_versions rv ON r.edit_of = rv.id
            )
            SELECT * FROM reply_versions
            ORDER BY created_at ASC
        """

        rows = await conn.fetch(query, reply_id)
        return [dict(row) for row in rows]

    @staticmethod
    async def can_edit_reply(
        conn: asyncpg.Connection,
        reply_id: int,
        user_id: int,
        time_limit_hours: int = 48
    ) -> Dict[str, Any]:
        """
        Check if reply can be edited by user.

        Checks:
        1. Reply exists and is posted (posted_at IS NOT NULL)
        2. User owns the reply (via task.assignee_user_id)
        3. Time limit not exceeded (< 48 hours since posted_at)

        Args:
            conn: Database connection
            reply_id: ID of reply to check
            user_id: User requesting edit
            time_limit_hours: Max hours since posting (default 48)

        Returns:
            {
                'can_edit': bool,
                'reason': str (if can_edit=False),
                'reply': Dict (reply data if exists),
                'hours_since_posted': float (if posted)
            }

        Reasons for can_edit=False:
        - 'not_found': Reply doesn't exist
        - 'not_posted': Reply not yet posted
        - 'time_expired': More than time_limit_hours passed
        - 'permission_denied': User doesn't own the reply

        Example:
            >>> result = await ReplyDAO.can_edit_reply(conn, reply_id=123, user_id=1)
            >>> if result['can_edit']:
            ...     print("User can edit this reply")
            ... else:
            ...     print(f"Cannot edit: {result['reason']}")
        """
        # Query with JOIN to tasks to check assignee_user_id and get platform info
        query = """
            SELECT
                r.id,
                r.task_id,
                r.content,
                r.generated_by,
                r.llm_confidence,
                r.confirmed,
                r.posted_at,
                r.platform_ref,
                r.edit_of,
                r.created_at,
                t.assignee_user_id,
                m.platform,
                m.channel_id,
                EXTRACT(EPOCH FROM (NOW() - r.posted_at))/3600 AS hours_since_posted
            FROM replies r
            INNER JOIN tasks t ON r.task_id = t.id
            INNER JOIN messages m ON t.source_message_id = m.id
            WHERE r.id = $1
        """

        row = await conn.fetchrow(query, reply_id)

        # Check 1: Reply exists
        if not row:
            return {
                'can_edit': False,
                'reason': 'not_found',
                'reply': None
            }

        reply_data = dict(row)

        # Check 2: Reply is posted
        if reply_data['posted_at'] is None:
            return {
                'can_edit': False,
                'reason': 'not_posted',
                'reply': reply_data
            }

        # Check 3: User owns the reply
        if reply_data['assignee_user_id'] != user_id:
            return {
                'can_edit': False,
                'reason': 'permission_denied',
                'reply': reply_data
            }

        # Check 4: Time limit not exceeded
        hours_since = reply_data['hours_since_posted']
        if hours_since > time_limit_hours:
            return {
                'can_edit': False,
                'reason': 'time_expired',
                'reply': reply_data,
                'hours_since_posted': hours_since
            }

        # All checks passed
        return {
            'can_edit': True,
            'reply': reply_data,
            'hours_since_posted': hours_since
        }

    @staticmethod
    async def create_edited_reply(
        conn: asyncpg.Connection,
        original_reply_id: int,
        new_content: str,
        user_id: int
    ) -> int:
        """
        Create new reply as edit of original.

        Creates:
        1. New reply with edit_of = original_reply_id
        2. Audit log entry ('reply.edit_started')

        Does NOT post to platform - caller must do that.

        Args:
            conn: Database connection
            original_reply_id: ID of reply being edited
            new_content: New reply text
            user_id: User performing edit

        Returns:
            new_reply_id: ID of newly created edited reply

        Raises:
            ValueError: If original_reply doesn't exist or validation fails

        Example:
            >>> new_id = await ReplyDAO.create_edited_reply(
            ...     conn=conn,
            ...     original_reply_id=123,
            ...     new_content='Updated reply text',
            ...     user_id=1
            ... )
            >>> print(f"Created edited reply with ID: {new_id}")
        """
        from .audit_dao import AuditDAO

        # 1. Validate using can_edit_reply
        validation = await ReplyDAO.can_edit_reply(
            conn, original_reply_id, user_id
        )

        if not validation['can_edit']:
            reason = validation.get('reason', 'unknown')
            error_messages = {
                'not_found': f"Reply {original_reply_id} does not exist",
                'not_posted': f"Reply {original_reply_id} has not been posted yet",
                'permission_denied': f"User {user_id} does not own reply {original_reply_id}",
                'time_expired': f"Reply {original_reply_id} edit time limit exceeded ({validation.get('hours_since_posted', 'N/A'):.1f} hours since posting)"
            }
            raise ValueError(error_messages.get(reason, f"Cannot edit reply: {reason}"))

        original_reply = validation['reply']
        task_id = original_reply['task_id']

        # 2. Create new reply with edit_of pointing to original
        insert_query = """
            INSERT INTO replies (
                task_id, content, generated_by, llm_confidence,
                confirmed, edit_of, created_at
            )
            VALUES ($1, $2, $3, $4, $5, $6, $7)
            RETURNING id
        """

        row = await conn.fetchrow(
            insert_query,
            task_id,
            new_content,
            original_reply['generated_by'],  # Preserve original generator type
            original_reply['llm_confidence'],  # Preserve LLM confidence if applicable
            False,  # Not confirmed yet (pending review)
            original_reply_id,  # edit_of
            datetime.utcnow()
        )

        new_reply_id = row['id']

        # 3. Create audit log entry
        audit_payload = json.dumps({
            'original_reply_id': original_reply_id,
            'new_reply_id': new_reply_id,
            'task_id': task_id,
            'user_id': user_id,
            'platform': original_reply.get('platform'),
            'channel_id': original_reply.get('channel_id'),
            'original_content_length': len(original_reply['content']),
            'new_content_length': len(new_content),
            'hours_since_posted': validation.get('hours_since_posted')
        })

        await AuditDAO.log_event(
            conn=conn,
            kind='reply.edit_started',
            payload_json=audit_payload,
            user_id=user_id
        )

        return new_reply_id
