"""
Reply Data Access Object.

Provides async database operations for replies table using asyncpg.
Handles moderator and LLM-generated replies to tasks.
"""

from datetime import datetime
from typing import Optional, List, Dict, Any
import asyncpg


class ReplyDAO:
    """
    Data Access Object for replies table.

    Manages replies generated by moderators or LLMs in response to tasks.
    """

    @staticmethod
    async def create_reply(
        conn: asyncpg.Connection,
        task_id: int,
        content: str,
        generated_by: str = 'human',
        llm_confidence: Optional[float] = None,
        edit_of: Optional[int] = None,
    ) -> int:
        """
        Create a new reply for a task.

        Args:
            conn: AsyncPG database connection
            task_id: ID of the task this reply addresses
            content: Reply text content
            generated_by: Reply source ('human' | 'llm') (default: 'human')
            llm_confidence: LLM confidence score 0.0-1.0 (optional, for LLM replies)
            edit_of: ID of original reply if this is an edit (optional)

        Returns:
            int: ID of the created reply

        Raises:
            asyncpg.ForeignKeyViolationError: If task_id or edit_of invalid
            asyncpg.PostgresError: On other database errors

        Example:
            >>> reply_id = await ReplyDAO.create_reply(
            ...     conn=conn,
            ...     task_id=42,
            ...     content='Thank you for your message!',
            ...     generated_by='human'
            ... )
        """
        query = """
            INSERT INTO replies (
                task_id, content, generated_by, llm_confidence,
                confirmed, edit_of, created_at
            )
            VALUES ($1, $2, $3, $4, $5, $6, $7)
            RETURNING id
        """

        row = await conn.fetchrow(
            query,
            task_id,
            content,
            generated_by,
            llm_confidence,
            False,  # Not confirmed by default
            edit_of,
            datetime.utcnow(),
        )

        return row['id']

    @staticmethod
    async def get_reply_by_id(
        conn: asyncpg.Connection,
        reply_id: int,
    ) -> Optional[Dict[str, Any]]:
        """
        Retrieve a reply by its ID.

        Args:
            conn: AsyncPG database connection
            reply_id: Reply ID

        Returns:
            Dictionary with reply data or None if not found

        Example:
            >>> reply = await ReplyDAO.get_reply_by_id(conn, 123)
            >>> if reply:
            ...     print(f"Content: {reply['content']}")
            ...     print(f"Confirmed: {reply['confirmed']}")
        """
        query = """
            SELECT
                id, task_id, content, generated_by, llm_confidence,
                confirmed, posted_at, platform_ref, edit_of, created_at
            FROM replies
            WHERE id = $1
        """

        row = await conn.fetchrow(query, reply_id)
        return dict(row) if row else None

    @staticmethod
    async def get_replies_for_task(
        conn: asyncpg.Connection,
        task_id: int,
        include_edits: bool = True,
    ) -> List[Dict[str, Any]]:
        """
        Retrieve all replies for a specific task.

        Args:
            conn: AsyncPG database connection
            task_id: Task ID
            include_edits: Include edited versions of replies (default: True)

        Returns:
            List of reply dictionaries ordered by created_at ASC

        Example:
            >>> replies = await ReplyDAO.get_replies_for_task(conn, task_id=42)
            >>> for reply in replies:
            ...     print(f"{reply['generated_by']}: {reply['content']}")
        """
        if include_edits:
            query = """
                SELECT
                    id, task_id, content, generated_by, llm_confidence,
                    confirmed, posted_at, platform_ref, edit_of, created_at
                FROM replies
                WHERE task_id = $1
                ORDER BY created_at ASC
            """
        else:
            query = """
                SELECT
                    id, task_id, content, generated_by, llm_confidence,
                    confirmed, posted_at, platform_ref, edit_of, created_at
                FROM replies
                WHERE task_id = $1 AND edit_of IS NULL
                ORDER BY created_at ASC
            """

        rows = await conn.fetch(query, task_id)
        return [dict(row) for row in rows]

    @staticmethod
    async def get_latest_reply_for_task(
        conn: asyncpg.Connection,
        task_id: int,
    ) -> Optional[Dict[str, Any]]:
        """
        Get the most recent reply for a task.

        Args:
            conn: AsyncPG database connection
            task_id: Task ID

        Returns:
            Dictionary with reply data or None if no replies exist

        Example:
            >>> latest = await ReplyDAO.get_latest_reply_for_task(conn, task_id=42)
        """
        query = """
            SELECT
                id, task_id, content, generated_by, llm_confidence,
                confirmed, posted_at, platform_ref, edit_of, created_at
            FROM replies
            WHERE task_id = $1
            ORDER BY created_at DESC
            LIMIT 1
        """

        row = await conn.fetchrow(query, task_id)
        return dict(row) if row else None

    @staticmethod
    async def mark_reply_confirmed(
        conn: asyncpg.Connection,
        reply_id: int,
    ) -> bool:
        """
        Mark a reply as confirmed by moderator.

        Used when a moderator approves an LLM-generated reply or confirms
        their own reply before sending.

        Args:
            conn: AsyncPG database connection
            reply_id: Reply ID

        Returns:
            True if reply was updated, False if reply not found

        Example:
            >>> confirmed = await ReplyDAO.mark_reply_confirmed(conn, reply_id=123)
        """
        query = """
            UPDATE replies
            SET confirmed = TRUE
            WHERE id = $1
        """

        result = await conn.execute(query, reply_id)
        return result.split()[-1] != '0'

    @staticmethod
    async def mark_reply_posted(
        conn: asyncpg.Connection,
        reply_id: int,
        platform_ref: str,
    ) -> bool:
        """
        Mark a reply as successfully posted to a platform.

        Args:
            conn: AsyncPG database connection
            reply_id: Reply ID
            platform_ref: JSON string with posting info
                         e.g., '{"platform": "discord", "message_id": "123"}'

        Returns:
            True if reply was updated, False if reply not found

        Example:
            >>> import json
            >>> ref = json.dumps({"platform": "discord", "message_id": "999"})
            >>> posted = await ReplyDAO.mark_reply_posted(conn, reply_id=123, platform_ref=ref)
        """
        query = """
            UPDATE replies
            SET posted_at = $1,
                platform_ref = $2
            WHERE id = $3
        """

        result = await conn.execute(
            query,
            datetime.utcnow(),
            platform_ref,
            reply_id,
        )

        return result.split()[-1] != '0'

    @staticmethod
    async def update_reply_content(
        conn: asyncpg.Connection,
        reply_id: int,
        new_content: str,
    ) -> bool:
        """
        Update the content of a reply.

        Note: For major changes, consider creating a new reply with edit_of
        pointing to the original instead.

        Args:
            conn: AsyncPG database connection
            reply_id: Reply ID
            new_content: New reply content

        Returns:
            True if reply was updated, False if reply not found

        Example:
            >>> updated = await ReplyDAO.update_reply_content(
            ...     conn, reply_id=123, new_content='Updated message'
            ... )
        """
        query = """
            UPDATE replies
            SET content = $1
            WHERE id = $2
        """

        result = await conn.execute(query, new_content, reply_id)
        return result.split()[-1] != '0'

    @staticmethod
    async def get_confirmed_replies(
        conn: asyncpg.Connection,
        task_id: Optional[int] = None,
        limit: int = 100,
    ) -> List[Dict[str, Any]]:
        """
        Retrieve confirmed replies, optionally filtered by task.

        Args:
            conn: AsyncPG database connection
            task_id: Filter by task ID (None for all tasks)
            limit: Maximum number of replies to return (default: 100)

        Returns:
            List of reply dictionaries ordered by created_at DESC

        Example:
            >>> confirmed = await ReplyDAO.get_confirmed_replies(conn, limit=50)
        """
        if task_id is not None:
            query = """
                SELECT
                    id, task_id, content, generated_by, llm_confidence,
                    confirmed, posted_at, platform_ref, edit_of, created_at
                FROM replies
                WHERE confirmed = TRUE AND task_id = $1
                ORDER BY created_at DESC
                LIMIT $2
            """
            rows = await conn.fetch(query, task_id, limit)
        else:
            query = """
                SELECT
                    id, task_id, content, generated_by, llm_confidence,
                    confirmed, posted_at, platform_ref, edit_of, created_at
                FROM replies
                WHERE confirmed = TRUE
                ORDER BY created_at DESC
                LIMIT $1
            """
            rows = await conn.fetch(query, limit)

        return [dict(row) for row in rows]

    @staticmethod
    async def get_posted_replies(
        conn: asyncpg.Connection,
        task_id: Optional[int] = None,
        limit: int = 100,
    ) -> List[Dict[str, Any]]:
        """
        Retrieve replies that have been posted to platforms.

        Args:
            conn: AsyncPG database connection
            task_id: Filter by task ID (None for all tasks)
            limit: Maximum number of replies to return (default: 100)

        Returns:
            List of reply dictionaries ordered by posted_at DESC

        Example:
            >>> posted = await ReplyDAO.get_posted_replies(conn, task_id=42)
        """
        if task_id is not None:
            query = """
                SELECT
                    id, task_id, content, generated_by, llm_confidence,
                    confirmed, posted_at, platform_ref, edit_of, created_at
                FROM replies
                WHERE posted_at IS NOT NULL AND task_id = $1
                ORDER BY posted_at DESC
                LIMIT $2
            """
            rows = await conn.fetch(query, task_id, limit)
        else:
            query = """
                SELECT
                    id, task_id, content, generated_by, llm_confidence,
                    confirmed, posted_at, platform_ref, edit_of, created_at
                FROM replies
                WHERE posted_at IS NOT NULL
                ORDER BY posted_at DESC
                LIMIT $1
            """
            rows = await conn.fetch(query, limit)

        return [dict(row) for row in rows]

    @staticmethod
    async def delete_reply(
        conn: asyncpg.Connection,
        reply_id: int,
    ) -> bool:
        """
        Delete a reply by ID.

        Args:
            conn: AsyncPG database connection
            reply_id: Reply ID

        Returns:
            True if reply was deleted, False if reply not found

        Example:
            >>> deleted = await ReplyDAO.delete_reply(conn, reply_id=123)
        """
        query = "DELETE FROM replies WHERE id = $1"
        result = await conn.execute(query, reply_id)
        return result.split()[-1] != '0'

    @staticmethod
    async def get_reply_history(
        conn: asyncpg.Connection,
        reply_id: int,
    ) -> List[Dict[str, Any]]:
        """
        Get edit history for a reply (all versions including the original).

        Args:
            conn: AsyncPG database connection
            reply_id: Original reply ID

        Returns:
            List of reply dictionaries showing edit history, ordered chronologically

        Example:
            >>> history = await ReplyDAO.get_reply_history(conn, reply_id=100)
            >>> for version in history:
            ...     print(f"Version {version['id']}: {version['content']}")
        """
        query = """
            WITH RECURSIVE reply_versions AS (
                -- Base case: the original reply
                SELECT
                    id, task_id, content, generated_by, llm_confidence,
                    confirmed, posted_at, platform_ref, edit_of, created_at
                FROM replies
                WHERE id = $1

                UNION ALL

                -- Recursive case: find all edits
                SELECT
                    r.id, r.task_id, r.content, r.generated_by, r.llm_confidence,
                    r.confirmed, r.posted_at, r.platform_ref, r.edit_of, r.created_at
                FROM replies r
                INNER JOIN reply_versions rv ON r.edit_of = rv.id
            )
            SELECT * FROM reply_versions
            ORDER BY created_at ASC
        """

        rows = await conn.fetch(query, reply_id)
        return [dict(row) for row in rows]
